### PR TITLE
Code refactoring to allow for expansion

### PR DESCRIPTION
**Pull request by Agriculturist**
This code is being modified for use in research involving flux measurements with open path line concentrations.  The internal functions of the code are not much different; however, the code was reorganized to reduce creep and make the code more modular.  More modular should make new features easier to add. Some new features have been added including:

1. Warning messages are formatted identically so it is clear the windrose function is generating the warning and it is not coming from outside the windrose function.

>`> windRose(mydata, breaks = "something wrong")`
Warning message:
In windRose(...):
breaks must be numeric
defaulting to breaks = 4 

2. Guards have been placed to check if the incoming data is in the correct form.  This may alleviate issue #103.  In the original implementation, if the incoming data is formatted wrong it is hard to tell what is wrong because errors may be anything generated anywhere.   

>`> windRose(1)`
`Error in windRose(1) : mydata must be of type data.frame'

3. More warnings are included so the user knows about situations like datapoints falling outside of the ws.int and/or breaks specifications.

> `windRose(mydata, breaks = c(0,5,10))`
Warning message:
In windRose(...):
Maximum value exceeded breaks 
breaks set to c(0, 5, 10, 20.16) 

4. A maximum can now be specified for the interval rings.  This is feature is intended to prevent the graph from displaying unrealistic frequency lines greater than 100%

>`windRose(mydata, grid.line = list(max = 15))`
image

5. The width of grid lines can be adjusted
`windRose(mydata, grid.line = list(lwd = 2))`

6. For big plots a finer circle can be made by doubling the resolution factor
`WindRose(mydata, grid.line = list(res = 2))`

7. An anticipated direction arrow can be added.  This is useful for determining if the wind blew in an anticipated direction.

> `windRose(mydata, grid.line = list(gridArrow = 180))`
image

8. The breaks are calculated differently.  If nothing is given pretty values are used.  If a vector is given then the vector is used.  If a vector is given, but not all the points are included a warning is issued before adding a break.

9.  Guards are on the custom statistics function.  If a custom function is not entered correctly a warning will be issued.  It is assumed custom functions are for advanced users so the guards are more intended to make finding typos easy.

10. dig.lab default was changed to 0... Not sure if this was for the best, but it is easy to change back.  It may be worth it to accept input as a named list so specific variables can be controlled.

Internal Changes to the code:

1. mydata is no longer treated as a mutable variable.  Changes are saved in the statdata variable instead.

2. windspeed and pollution are better separated. If a variable says wind speed then it is more likely windspeed.

3. As best as possible limited the characters per line to 80 so it displays well on most screens.

4. As best as possible removed dots (.) from name to avoid confusion with the dot operator.  lower camel case was used instead.

5. Avoided repetition of code as much as possible.

6. Used functions to delineate tasks such as drawing the individual elements.  This should make the code much simpler to upgrade.

7. The name 'results' has been changed to 'pltData' because with results it is confusing about which results. 

8. Angle360 function automatically coerces angles between (0 - 360]

9. DegtoRad performs the degrees to radians calculation

10.  One computation was confusing...  

The wind direction is set into intervals
line 533 -  
`mydata[[wd]] <- angle * ceiling(mydata[[wd]] / angle - 0.5)`

Then the average wind direction is calculated from the angles set to intervals
line 610 -  
`## calculate mean wd - useful for cases comparing two met data sets`
`u <- mean(sin(2 * pi * mydata[[wd]] / 360), na.rm = TRUE)`
`v <- mean(cos(2 * pi * mydata[[wd]] / 360), na.rm = TRUE)`
`mean.wd <- atan2(u, v) * 360 / 2 / pi`

The proposed version works differently. The averages wind direction is calculated from non-interval data.

11. The concept of an apothem is introduced to make understanding lengths in the plot simple.  The apothem of a square goes from the center to the mid-point of one of the sides.

12.  This code is broken apart into major sections and minor subsections.  This code was rearranged so code fell into the correct section.   Because of this reorganization it is very hard to see where the changes in the code occurred.  Hopefully the sections of code are intuitive.

In progress:
1. Plotting a point with the average wind speed and direction directly on the wind rose.  This will be used as a means to determine the quality of an average wind speed and direction.  This feature is already included, but the average wind speed is in the wrong spot.

### CODE REVIEW

**Comment by Agriculturist** [comment]
The check did not like dig.lab default value being changed.

**Comment by davidcarslaw** [comment]
This is a significant contribution - thank you! 

I have made a new branch `windRose_refactor`. There are a few things that I need to test e.g. that it does not break existing functionality (there is an issue with `pollutionRose` that I will look at). 

The other issue is whether the new default way of handing breaks in `windRose` causes too much of a change in default behaviour. For example, previous behaviour with `windRose(mydata)` produced breaks of 0, 2, 4, 6, 6 - 20.16, controlled by `ws.int`). The new behaviour gives intervals of 5 to 25 i.e. ignores `ws.int`. I think I prefer the existing behaviour here - have you got views on this? My reason is that because wind speed distributions are so skewed, there is little information in the top few intervals when they are equally spaced.

The existing code was a bit of a mess to be honest because it had been hacked about by a few people - so your efforts to sort that out are much appreciated. I think if we can solve a few issues / deal with consistency with past behaviour, this will be a great foundation on which to build.

Thanks again!

David

**Comment by Agriculturist** [comment]
Sometimes the code would stop in an unusual location such as in the middle of a dependency when the data was inadvertently entered incorrectly.  Because the location of the stop was nowhere near the actual error,  debugging sometimes proved difficult.  To prevent these stops the code was altered to include guards.  The guards added to **_ws.int_** and **_breaks_** changed the code behavior.  The software changes needed to approximate the old behavior are trivial.  

Dropbox is something I do not have access; however, in the online openair manual, I could not find an explanation for the interval produced when the maximum determined by **_ws.int_** and **_breaks_** is exceeded.  Upon closer examination I am guessing this interval accounts for gusts which are higher than the specified range.  This is different from base r behavior.   
```
someData <-rnorm(n=1000, m=0, sd=1)
hist(someData, breaks=c(-4,-2,0,2,4))
hist(someData, breaks=c(-4,-2,0,2))
Error in hist.default(someData, breaks = c(-4, -2, 0, 2)) : 
  some 'x' not counted; maybe 'breaks' do not span range of 'x'
```

The reasoning behind the extra interval needs explaining to prevent confusion.  Perhaps in the description of the breaks parameter.    

Would these code changes work?…  

- If breaks is something it is not supposed to be the guards will change it to default and issue a warning to the user.
- If breaks is a numeric or default then ws.int and breaks are used as an estimated bin number to generate a breaks vector.  The first element of the break is always 0. If the last break is less than the wind speed maximum then another interval is added up to the range of the maximum windspeed.  
- If breaks parameter is directly specified as a vector.  Then only the last break is generated the maximum wind speed does not cover the interval.
- If breaks is specified as a list with “noMaxInterval” present then the breaks will be processed as before (vector or numeric) except without the final interval.  A warning if the maximum wind speed exceeds the intervals will be issued instead.

**Comment by davidcarslaw** [comment]
Thanks for the continued development of this function. There are a few things it would be useful to check.

The rounding of scale values needs refinement e.g. see wind rose below.
image

Also, the comparison of two data sets does not yield the expected results as shown in the manual. Try:

```
## $example of comparing 2 met sites
## first we will make some new ws/wd data with a postive bias
mydata <- transform(mydata,
ws2 = ws + 2 * rnorm(nrow(mydata)) + 1,
wd2 = wd + 30 * rnorm(nrow(mydata)) + 30)
## need to correct negative wd
id <- which(mydata$wd2 < 0)
mydata$wd2[id] <- mydata$wd2[id] + 360
## results show postive bias in wd and ws
pollutionRose(mydata, ws = "ws", wd = "wd", ws2 = "ws2", wd2 = "wd2", grid.line = 5)
```

You have made a lot of changes that I believe will increase the robustness of the function as well as make it more flexible. There is quite a lot to go through here and I still need to think about some of the things myself. I wondered whether you would consider writing a vignette on this function - it might be a useful way of demonstrating its use and capabilities?

I shall continue to have a look at this - but thanks for the effort!

**Comment by Agriculturist** [comment]
I will see if I can break apart the refactoring

**Pull request closed without merging**
